"""Add text color fields to UserPreference

Revision ID: c5b4b5cd4bab
Revises: ea211be45f1e
Create Date: 2025-08-03 00:25:19.008832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b4b5cd4bab'
down_revision = 'ea211be45f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('custom_text_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('custom_text_color')
        batch_op.drop_column('text_color')

    # ### end Alembic commands ###
