"""Add custom color fields to UserPreference

Revision ID: ea211be45f1e
Revises: 8176a87c26ef
Create Date: 2025-08-03 00:11:24.710171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea211be45f1e'
down_revision = '8176a87c26ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_primary_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('custom_secondary_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('custom_secondary_color')
        batch_op.drop_column('custom_primary_color')

    # ### end Alembic commands ###
