"""Add missing fields to Company and Project models

Revision ID: f50de4be4392
Revises: 9bde8137f23b
Create Date: 2025-08-01 23:29:05.168943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50de4be4392'
down_revision = '9bde8137f23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('budget')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('website')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
